project:
  type: website
  
website:
  title: "DUG::conf"
  # margin-header: |
  #   ![Logo image](/images/dugheader2.png){width=120%}
  # body-header: |
  #   ![Logo image](/images/dugheader2.png){width=120%}
  google-analytics: "G-SDBDVSXSRC"
  sidebar:
    logo: "/images/dugheader2.png"
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - posts.qmd
      - section: "R Resources"
        contents: 
        - text: "Books"
          href: r-books.qmd
        - text: "Blogs"
          href: r-blogs.qmd
      - section: "Meetings"
        contents: 
          - section: "2025-07-17"
            contents: 
            - text: "Fork Me! Why You Should Learn GitHub"
              href: github-presentation.qmd
            - text: "Survey Platform: SurveyDown"
              href: https://jasonlocklin.github.io/surveydown-presentation/#/title-slide
            - text: "Maps with the `sf` Package"
              href: maps-with-sf.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



