project:
  type: website
  output-dir: docs

website:
  title: "DUG::conf"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - section: "R Resources"
        contents:
          - r-resources.qmd
          - ggplot-2.qmd
      - section: "Power BI"
        contents: 
          -power-bi.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

