project:
  type: website
  
website:
  title: "DUG::conf"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - section: "R Resources"
        href: r-resources.qmd
        contents:
          - ggplot-2.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

