project:
  type: website
  
website:
  title: "DUG::conf"
  body-header: | 
    ![Logo image](/images/dugheader2.png){width=120%}
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - section: "R Resources"
        href: r-resources.qmd
        contents:
          - text: "R Books"
            href: r-books.qmd
          - text: "Fork me!"
            href: github-presentation.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



