name: Quarto Publish

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push to gh-pages

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install tidyverse
        run: |
          install.packages(c("tidyverse", "usethis", "pkgdown", "rcmdcheck", "rversions", "urlchecker"), repos = "https://cloud.r-project.org")          
        shell: Rscript {0}

      - name: Install devtools
        run:
          install.packages("devtools", repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Install TCDSB package
        run:
          devtools::install_github("grousell/tcdsb")
        shell: Rscript {0}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Create .nojekyll file
        run: echo "" > .nojekyll

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages

